# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm and dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && \
    pnpm install --frozen-lockfile

# Copy source code
COPY . .

# Build TypeScript sources
RUN pnpm run build

# Default command uses MCP stdio protocol, CHAINGPT_SECRET_KEY should be provided at runtime via env
CMD ["node", "build/index.js"]
